CREATE TABLE organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(200) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, description VARCHAR(500), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE roles ADD CONSTRAINT fk_roles_organization FOREIGN KEY (organization_id) REFERENCES organizations(id);
CREATE TABLE employees (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), user_id UUID NOT NULL UNIQUE REFERENCES users(id), job_title VARCHAR(150), phone VARCHAR(40), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE departments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), name VARCHAR(150) NOT NULL, description VARCHAR(500), UNIQUE(organization_id,name));
CREATE TABLE teams (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), department_id UUID REFERENCES departments(id), name VARCHAR(150) NOT NULL, description VARCHAR(500), UNIQUE(organization_id,name));
CREATE TABLE projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), name VARCHAR(200) NOT NULL, description VARCHAR(1000), status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', start_date DATE, due_date DATE, UNIQUE(organization_id,name));
CREATE TABLE tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), project_id UUID NOT NULL REFERENCES projects(id), team_id UUID REFERENCES teams(id), assignee_id UUID REFERENCES employees(id), title VARCHAR(250) NOT NULL, description VARCHAR(2000), status VARCHAR(30) NOT NULL DEFAULT 'TODO', priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM', due_date DATE);
CREATE INDEX idx_workspace_org ON employees(organization_id); CREATE INDEX idx_departments_org ON departments(organization_id); CREATE INDEX idx_teams_org ON teams(organization_id); CREATE INDEX idx_projects_org ON projects(organization_id); CREATE INDEX idx_tasks_org ON tasks(organization_id);
